enum ActionTypes {
  API_CALL_REQUEST = 'API_CALL_REQUEST',
  API_CALL_FAILURE = 'API_CALL_FAILURE',
  API_CALL_SUCCESS = 'API_CALL_SUCCESS',
  SUCCESS_OPERATION = 'SUCCESS_OPERATION',
  GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST',
  GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS',
  SELECT_MOVIE = 'SELECT_MOVIE',
  GET_SERIES_SUCCESS = 'GET_SERIES_SUCCESS',
  GET_SERES_REQUEST = 'GET_SERES_REQUEST',
  SELECT_SERIE = 'SELECT_SERIE',
  RESET_COLLECTION = 'RESET_COLLECTION',
}

export default ActionTypes;
